version: 2
updates:
  - package-ecosystem: npm
    directory: /.github/scripts
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /app/assets/scaffold/files
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /plugins/GrapesJsBuilderBundle
    schedule:
      interval: daily
