name: Build JS files for dist folder

on:
  # Allow manually triggering this workflow
  workflow_dispatch:
  schedule:
    # Run every day at 10 AM UTC
    - cron: '0 10 * * *'

defaults:
  run:
    working-directory: plugins/GrapesJsBuilderBundle

permissions:
  contents: read

jobs:
  build-js:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    if: github.repository == 'mautic/mautic'

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Build JS dist files
      run: npm run build

    # Checks if the JS files have been updated as a result of the NPM build,
    # and creates a PR if necessary.
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672 # v3.14.0
      with:
        commit-message: 'Auto-update GrapesJS generated JS dist files'
        title: 'Update GrapesJS generated JS dist files'
        delete-branch: true
