name: Mautic tests and validations

on:
  push:
    branches:
      - staging
      - features
      - '[0-9]+\.[0-9]+'
  pull_request:

jobs:
  tmate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Debugging with tmate
      uses: mxschmitt/action-tmate@v3.5
